name: Lint Test

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: '1.18.18'
  RUST_TOOLCHAIN: stable

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -A clippy::pedantic --deny=warnings